export * as AuthService from './AuthService'
export * as VandorService from './VandorService'
export * as FoodService from './FoodService'
export * as AdminService from './AdminService'
export * as CustomerService from './CustomerService'
